;; Stolen from https://github.com/dawranliou/emacs.d/blob/master/themes/alabaster-theme.el

(deftheme alabaster
  "https://github.com/tonsky/sublime-scheme-alabaster")
(custom-theme-set-faces
 'alabaster
 '(cursor ((t (:background "#007ACC"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t nil)))
 '(font-lock-comment-delimiter-face ((t (:background "#FFFABC" :extend t))))
 '(font-lock-comment-face ((t (:background "#FFFABC" :extend t))))
 '(font-lock-constant-face ((t (:foreground "#7A3E9D"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:background "#FFFABC" :extend t))))
 '(font-lock-doc-markup-face ((t (:background "#FFFABC" :extend t))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-name-face ((t nil)))
 '(font-lock-keyword-face ((t nil)))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-property-face ((t (:background "#DBF1FF"))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:background "#F1FADF"))))
 '(font-lock-type-face ((t nil)))
 '(font-lock-variable-name-face ((t (:bold t))))
 '(font-lock-warning-face ((t (:background "#FFE0E0" :foreground "#C33"))))
 '(lazy-highlight ((t (:background "#DBF1FF")))))
(provide-theme 'alabaster)
