alias ls="ls --color=auto"
alias grep="grep --color=auto"

alias ll="ls -l"
alias la="ls -a"
alias lla="ls -la"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
